site:
  title: Foreman Documentation
  start_page: component-b::index.adoc
content:
  sources:
  - url: https://github.com/theforeman/foreman-documentation
    branches:
      - 'master'
      - '3.4'
      - '3.3'
      - '3.2'
      - '3.1'
      - '3.0'
      - '2.5'
      - '2.4'
    start_path: guides
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
