name: comment-on-pr example
on: pull_request
jobs:
  branches:
    name: Determine branches
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.parse.outputs.versions }}
    steps:
      - name: Parse PR message - cat
        run: |
          cat <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - awk 0
        run: |
          awk '/Foreman [0-9]+\.[0-9]+/ { print $4 }' <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - awk 1
        run: |
          awk '/Foreman [0-9]+\.[0-9]+$/ { print $4 }' <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - awk 2
        run: |
          awk '/\[x\] Foreman/ { print $4 }' <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - awk 3
        run: |
          awk '/\* \[x\] Foreman/ { print $4 }' <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - awk 4
        run: |
          awk '/^\* \[x\] Foreman/ { print $4 }' <<EOF
          ${{ github.event.pull_request.body }}
          EOF
