name: comment-on-pr example
on: pull_request
jobs:
  branches:
    name: Determine branches
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.parse.outputs.versions }}
    steps:
      - name: Parse PR message - cat
        run: |
          cat <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - awk
        run: |
          awk '/^\* \[x\] Foreman [0-9]+\.[0-9]+$/ { print $4 }' <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - gawk
        run: |
          gawk '/^\* \[x\] Foreman [0-9]+\.[0-9]+$/ { print $4 }' <<EOF
          ${{ github.event.pull_request.body }}
          EOF
      - name: Parse PR message - awk + python
        run: |
          awk '/^\* \[x\] Foreman [0-9]+\.[0-9]+$/ { print $4 }' <<EOF | python3 -c 'import json, sys ; print(f"::set-output versions={json.dumps(sys.stdin.read().split())}")'
          ${{ github.event.pull_request.body }}
          EOF
